/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package grdle_enumclass;

public class App {

    String nama;
    public App(String nama){
        this.nama=nama;
    }
    
    public void setNama(String nama){
        
        System.out.println("namanya adalah : " + nama);
    }

    public String getNama(){
        return nama;
    }
    /*
    public String getGreeting() {
        return "Hello world.";
    }
    */

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        //App app = new App();
           // System.out.println(app);

           //app.setNama("panji");
           //System.out.println(app.getNama);

           SetNama settNama = new SetNama();

        settNama.setNama("anggun");
    System.out.println(getNama);

        
    }
}
